name: Build and Publish to JFrog Artifactory

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile and Test
      run: ./mvnw clean test

    - name: Build Docker Image
      run: ./mvnw spring-boot:build-image

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      with:
        version: latest

    - name: Publish Docker Image
      run: |
        jfrog rt docker-push <YOUR-IMAGE-NAME>:<YOUR-TAG> <YOUR-TARGET-REPOSITORY>
        jfrog rt bp <BUILD-NAME> <BUILD-NUMBER>