name: Build and Publish to JFrog Artifactory

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile and Test
      run: ./mvnw clean test

    - name: Build Docker Image
      run: ./mvnw spring-boot:build-image

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

    - name: Tag and Push Docker Image
      env:
        IMAGE_NAME: surfergolfer.jfrog.io/rapid-test-docker/jfrog-docker-example-image:${{ github.run_number }}
      run: |
          docker tag docker.io/library/spring-petclinic:3.1.0-SNAPSHOT $IMAGE_NAME
          jf docker push $IMAGE_NAME
  
    - name: Publish Build info With JFrog CLI
      env:
        JFROG_CLI_BUILD_NAME: jfrog-docker-build-demo
        JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
      run: |
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish

    - name: Xray Scan
      run: |
        jfrog rt build-scan jfrog-docker-build-demo ${{ github.run_number }}
