name: Build and Publish to JFrog Artifactory

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile and Test
      run: ./mvnw clean test

    - name: Build Docker Image
      run: ./mvnw spring-boot:build-image

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

    - name: Publish Docker Image
      run: |
        jfrog rt docker-push docker.io/library/spring-petclinic:3.1.0-SNAPSHOT:1.0.0 surfergolfer.jfrog.io/prd-spring-dev-docker/rapid-test-image
        jfrog rt bp rapid-test-image 1.0.0